image: python:3.8.16-alpine3.17

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

stages:
  - publish

cache:
  paths:
    - .cache/pip
    - venv/

build_docker:
  stage: publish
  image:
    name: gcr.io/kaniko-project/executor:v1.14.0-debug
    entrypoint: [""]
  script:
    - export CODE_VERSION=$(cat VERSION)
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}/niryo_ned"
      --dockerfile "${CI_PROJECT_DIR}/niryo_ned/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}:${CODE_VERSION}"
      --destination "${CI_REGISTRY_IMAGE}:latest"
  rules:
    - if: $CI_COMMIT_BRANCH == "main"

