version: "3"
services:
  niryo-ned-2:
    container_name: niryo-ned-2
    build: ./niryo_ned
    ports:
      - "8000:8000"
    restart: unless-stopped
    stdin_open: true
    tty: true
  prometheus:
    container_name: prometheus-svc
    depends_on:
      - niryo-ned-2
    ports:
      - "9000:9090"
    image: prom/prometheus
    command: --config.file=/etc/prometheus/prometheus.yaml
    volumes:
      - ./prometheus/:/etc/prometheus/
    stdin_open: false

networks:
  metrics: