# my global config
global:
  scrape_interval: 1s # Set the scrape interval to every 1 seconds. Default is every 1 minute.
  evaluation_interval: 1s # Evaluate rules every 1 seconds. The default is every 1 minute.
scrape_configs:
  - job_name: niryo_ned_2
    static_configs:
      - targets: ["niryo-ned-2:8000"]