apiVersion: v1
kind: Service
metadata:
  name: niryo-ned-2
  # namespace: my-namespace
spec:
  type: NodePort
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30000 # Change this to any available port in your cluster
  selector:
    app: niryo-ned-2