apiVersion: apps/v1
kind: Deployment
metadata:
  name: niryo-ned-2
  # namespace: my-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: niryo-ned-2
  template:
    metadata:
      labels:
        app: niryo-ned-2
    spec:
      containers:
        - name: niryo-ned-2
          image: remote-control-niryo-ned-2-niryo-ned-2
          ports:
            - containerPort: 8000
          stdin: true
          tty: true
      imagePullSecrets:
      - name: docker-pull-secret   

