apiVersion: apps/v1
kind: Deployment
metadata:
  name: niryo-ned-2
  namespace: my-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: niryo-ned-2
  template:
    metadata:
      labels:
        app: niryo-ned-2
    spec:
      containers:
        - name: niryo-ned-2
          image: <your-niryo-ned-image> # Replace with the image name or build it using an external CI/CD
          ports:
            - containerPort: 8000
          stdin: true
          tty: true
