apiVersion: v1
kind: Service
metadata:
  name: prometheus-svc
  namespace: my-namespace
spec:
  type: NodePort
  ports:
    - port: 9090
      targetPort: 9090
      nodePort: 30001 # Change this to any available port in your cluster
  selector:
    app: prometheus
