apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  # namespace: my-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
      - name: prometheus
        image: {.Values.prometheus-deployment.image.repository}{.Values.prometheus-deployment.image.tag}
        pullPolicy: {.Values.prometheus-deployment.image.pullPolicy}
        args:
          - --config.file=/etc/prometheus/prometheus.yaml
        ports:
          - containerPort: 9090
        volumeMounts:
          - name: prometheus-config
            mountPath: /etc/prometheus/
      volumes:
        - name: {.Values.prometheus-deployment.volumes.name}
          hostPath: 
            path: {.Values.prometheus-deployment.volumes.hostPath}